# Generated by Django 5.1 on 2024-08-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userchatactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatactivity',
            name='last_joined_time',
            field=models.DateTimeField(),
        ),
    ]
